name:Hello World Workflow

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:
jobs:
  hello:
    runs-on:ubuntu-latest
    steps:
      -uses:actions/checlkout@v4
      -name:hello world
       run:echo "Hello World"
       shell:bash
  goodbye:
    runs-on:ubuntu-latest
    steps:
      -name:goodbye world
       run:echo "Bye Bye World"
       shell:bash
