name: Create a new issue file

on:
  issues:
    types: [opened]
jobs:
  comment with actions:
     runs-on: ubuntu-latest
     steps: 
       - name: run Github Context
         run: echo '${{ toJSON(github.event) }}' | jq
         shell: bash
