name: Create a comment on issues

on:
  issues:
    types: [opened]
jobs:
  comment-a-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{toJson(github.event) }}' | jq
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: 16
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create an api account
        run: |
          gh api -X POST \
          http://api.github.com/repo/${ORGANIZATION}/{REPOSITORY}/issueS/{ISSUE_NUMBER/comments\ 
          -f body='
          COMMENT FROM THE API BUT NOT FROM THE API CALL
          '
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ORGANIZATION: ${{ github.event.organization.login }}
            REPOSITORY: ${{ github.event.repository.name }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
          
  
